<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
    <TargetFrameworks>net10.0-browser</TargetFrameworks>

	<OutputType>Library</OutputType>
	<WasmBuildNative>false</WasmBuildNative>
	<HasRuntimeOutput>false</HasRuntimeOutput>

	<RootNamespace>Atrium</RootNamespace>
	<AssemblyName>$(RootNamespace)</AssemblyName>

    <EnableDefaultCssItems>false</EnableDefaultCssItems>
    <Nullable>enable</Nullable>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<ImplicitUsings>disable</ImplicitUsings>
	
		
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>

    <WindowsPackageType>None</WindowsPackageType>

	<UsingMicrosoftNETSdkRazor>true</UsingMicrosoftNETSdkRazor>
	<BaseOutputPath>bin\Wasm\</BaseOutputPath>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.*-*" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.6" />
	</ItemGroup>

	
  <ItemGroup>
    <Compile Remove="Platforms\**" />
    <EmbeddedResource Remove="Platforms\**" />
    <None Remove="Platforms**" />
  </ItemGroup>
	
	
  <ItemGroup>
    <Compile Remove="Components\MainLoader.razor.cs" />
  </ItemGroup>
	
  <ItemGroup>
    <Content Remove="wwwroot\index.html" />
  </ItemGroup>

	<ItemGroup>
	  <Folder Include="Platforms\" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="App.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </None>
	</ItemGroup>

</Project>
