<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<OutputType>Library</OutputType>
		<HasRuntimeOutput>false</HasRuntimeOutput>
		<RootNamespace>Recollect</RootNamespace>
		<AssemblyName>$(RootNamespace)</AssemblyName>
	</PropertyGroup>
	
</Project>
