<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFrameworks>net10.0-browser</TargetFrameworks>
		<OutputType>Library</OutputType>
		<HasRuntimeOutput>false</HasRuntimeOutput>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<RootNamespace>Hosting</RootNamespace>
		<AssemblyName>$(RootNamespace)</AssemblyName>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-browser'">
		<PackageReference Include="Microsoft.AspNetCore.Components" Version="10.0.*-*" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.*-*" />
		<PackageReference Include="Microsoft.AspNetCore.Authorization" Version="10.0.*-*" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Forms" Version="10.0.*-*" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.*-*" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client.Core" Version="10.0.*-*" />
	</ItemGroup>



	<ItemGroup>
	  <ProjectReference Include="..\DataShared\DataShared.csproj" />
	  <ProjectReference Include="..\Extensions\Extensions.csproj" />
	  <ProjectReference Include="..\RazorSharp\RazorSharp.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Platforms\Windows\Startup.cs">
	    <ExcludeFromCurrentConfiguration>true</ExcludeFromCurrentConfiguration>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <Content Update="wwwroot\offline.js">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

</Project>


