<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<OutputType>Library</OutputType>
		<HasRuntimeOutput>false</HasRuntimeOutput>
		<RootNamespace>LiveTest</RootNamespace>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.*-*" />
	</ItemGroup>

</Project>
