<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<RootNamespace>Clippy</RootNamespace>
		<AssemblyName>$(RootNamespace)</AssemblyName>
	</PropertyGroup>
	
	<ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.Components" Version="10.0.*-*" />
	  <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.*-*" />
	  <PackageReference Include="Microsoft.JSInterop" Version="10.0.*-*" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Extensions\Extensions.csproj" />
	</ItemGroup>

</Project>
