using System.Text.RegularExpressions;

namespace DataLayer.Utilities
{
    public static class FingerPrint
    {

        public static long Text(string text)
        {
            // 1. Tokenize and clean (Lowercase, remove punctuation)
            var tokens = text.ToLower().Split(' ', StringSplitOptions.RemoveEmptyEntries);

            // 2. Hash each token and weigh them
            int[] v = new int[64];
            foreach (var token in tokens)
            {
                long hash = GetFNV1aHash(token); // Standard 64-bit hash
                for (int i = 0; i < 64; i++)
                {
                    // Bitwise weighting
                    if (((hash >> i) & 1) == 1) v[i]++;
                    else v[i]--;
                }
            }

            // 3. Fingerprint construction
            long fingerprint = 0;
            for (int i = 0; i < 64; i++)
            {
                if (v[i] > 0) fingerprint |= (1L << i);
            }
            return fingerprint;
        }

        public static long GetFNV1aHash(string text)
        {
            // FNV-1a constants for 64-bit
            const ulong offsetBasis = 0xcbf29ce484222325;
            const ulong prime = 0x100000001b3;

            ulong hash = offsetBasis;

            // Use unchecked to allow the math to wrap around naturally
            unchecked
            {
                foreach (char c in text)
                {
                    // FNV-1a order: XOR then Multiply
                    hash ^= (ushort)c;
                    hash *= prime;
                }
            }

            // Return as long for database compatibility (BIGINT)
            return (long)hash;
        }

        public static readonly Dictionary<string, string[]> StopWords = new()
        {
            { "en", new[] { "a", "an", "and", "are", "as", "at", "be", "but", "by", "for", "if", "in", "is", "it", "no", "not", "of", "on", "or", "such", "that", "the", "their", "then", "there", "these", "they", "this", "to", "was", "will", "with" } },
            { "es", new[] { "al", "ante", "bajo", "con", "contra", "de", "del", "desde", "durante", "el", "ella", "ellos", "en", "entre", "es", "esta", "esto", "hacia", "hasta", "la", "las", "lo", "los", "mas", "mi", "mis", "ni", "no", "nos", "o", "para", "pero", "por", "que", "se", "si", "sin", "sobre", "su", "sus", "te", "tu", "un", "una", "unas", "uno", "unos", "y" } },
            { "fr", new[] { "au", "aux", "avec", "ce", "ces", "dans", "de", "des", "du", "elle", "en", "et", "eux", "il", "ils", "je", "la", "le", "les", "leur", "lui", "ma", "mais", "me", "même", "mes", "moi", "mon", "ne", "nos", "notre", "nous", "on", "ou", "par", "pas", "pour", "qu", "que", "qui", "sa", "se", "ses", "son", "sur", "ta", "te", "tes", "toi", "ton", "tu", "un", "une", "vos", "votre", "vous" } },
            { "de", new[] { "aber", "alle", "allem", "allen", "aller", "alles", "als", "am", "an", "ander", "andere", "anderem", "anderen", "anderer", "anderes", "anderm", "andern", "anderr", "anders", "auch", "auf", "aus", "bei", "bin", "bis", "bist", "da", "damit", "dann", "der", "den", "des", "dem", "die", "das", "daß", "dass", "dein", "deine", "deinem", "deinen", "deiner", "deines", "denn", "derer", "dessen", "dich", "dir", "du", "dies", "diese", "diesem", "diesen", "dieser", "dieses", "doch", "dort", "durch" } },
            { "pt", new[] { "a", "ao", "aos", "aquela", "aquelas", "aquele", "aqueles", "aquilo", "as", "até", "com", "como", "da", "das", "de", "dela", "delas", "dele", "deles", "depois", "do", "dos", "e", "é", "ela", "elas", "ele", "eles", "em", "entre", "era", "eram", "essa", "essas", "esse", "esses", "esta", "estamos", "estão", "estas", "este", "estes", "estou", "eu", "foi", "fomos", "foram", "fosse", "fossem", "ha", "haja", "hajam", "houve", "houvemos", "houveram", "isso", "isto", "já", "lhe", "lhes", "mais", "mas", "me", "mesmo", "meu", "meus", "minha", "minhas", "muito", "na", "nas", "nem", "no", "nos", "nossa", "nossas", "nosso", "nossos", "num", "numa", "o", "os", "ou", "para", "pela", "pelas", "pelo", "pelos", "por", "qual", "quando", "que", "quem", "se", "seja", "sejam", "seu", "seus", "só", "somos", "sou", "sua", "suas", "também", "te", "tem", "tém", "temos", "teu", "teus", "tu", "tua", "tuas", "um", "uma", "você", "vocês", "vos" } },
            { "ru", new[] { "а", "без", "более", "бы", "был", "была", "были", "было", "быть", "в", "вам", "вас", "весь", "во", "вот", "все", "всего", "всех", "вы", "где", "да", "даже", "для", "до", "его", "ее", "если", "есть", "еще", "же", "за", "здесь", "и", "из", "или", "им", "их", "к", "как", "ко", "когда", "кто", "ли", "меня", "мне", "много", "может", "на", "над", "надо", "нас", "не", "него", "нее", "нет", "ни", "них", "но", "ну", "о", "об", "однако", "он", "она", "они", "оно", "от", "очень", "по", "под", "при", "с", "себе", "себя", "со", "так", "такой", "там", "те", "тебя", "тем", "теперь", "ти", "то", "того", "тоже", "только", "том", "тот", "три", "тут", "ты", "у", "уж", "хотя", "чего", "чей", "чем", "что", "чтоб", "чтобы", "чуть", "эти", "этого", "этот", "эту", "я" } },
            { "it", new[] { "a", "abbia", "abbiano", "abbiamo", "abbiate", "ad", "agl", "agli", "al", "all", "alla", "alle", "allo", "anche", "ante", "avemmo", "avendo", "avesse", "avessero", "avessi", "avessimo", "aveste", "avesti", "avete", "aveva", "avevamo", "avevano", "avevate", "avevi", "avevo", "avrai", "avranno", "avrebbe", "avrebbero", "avrei", "avremmo", "avremo", "avreste", "avresti", "avrete", "avrò", "avuta", "avute", "avuti", "avuto", "che", "chi", "ci", "coi", "col", "come", "con", "contro", "cui", "da", "dagl", "dagli", "dal", "dall", "dalla", "dalle", "dallo", "degl", "degli", "dei", "del", "dell", "della", "delle", "dello", "di", "dov", "dove", "e", "ebbe", "ebbero", "ebbi", "ed", "era", "erano", "eravamo", "eravate", "eri", "ero", "essendo", "faccia", "facciano", "facciamo", "facciate", "fecero", "feci", "fosse", "fossero", "fossi", "fossimo", "foste", "fosti", "fu", "fummo", "fui", "gli", "ha", "hai", "hanno", "ho", "i", "il", "in", "io", "l", "la", "le", "lei", "li", "lo", "loro", "lui", "ma", "mi", "mia", "mie", "miei", "mio", "ne", "negl", "negli", "nei", "nel", "nell", "nella", "nelle", "nello", "no", "noi", "non", "nostra", "nostre", "nostri", "nostro", "o", "per", "perché", "più", "quale", "quanta", "quante", "quanti", "quanto", "quella", "quelle", "quelli", "quello", "questa", "queste", "questi", "questo", "sarai", "saranno", "sarebbe", "sarebbero", "sarei", "saremmo", "saremo", "sareste", "saresti", "sarete", "sarò", "se", "sei", "si", "sia", "siano", "siamo", "siate", "siete", "sono", "sta", "stai", "stanno", "stia", "stiano", "stiamo", "stiate", "sto", "su", "sua", "sue", "sugl", "sugli", "sui", "sul", "sull", "sulla", "sulle", "sullo", "suo", "suoi", "ti", "tra", "tu", "tua", "tue", "tuoi", "tuo", "tutti", "tutto", "un", "una", "uno", "vi", "voi", "vostra", "vostre", "vostri", "vostro" } },
            { "nl", new[] { "aan", "af", "al", "als", "bij", "dan", "dat", "de", "den", "der", "des", "deze", "die", "dit", "door", "een", "en", "enige", "enkele", "er", "ga", "ge", "geen", "geweest", "haar", "had", "heb", "hebben", "heeft", "hem", "hen", "het", "hier", "hij", "hoe", "hun", "iemand", "iets", "ik", "in", "is", "it", "ja", "je", "kan", "kon", "kunnen", "maar", "me", "meer", "men", "met", "mij", "mijn", "moet", "na", "naar", "niet", "niets", "nog", "nu", "of", "om", "omdat", "onder", "ons", "ook", "op", "over", "reeds", "te", "tegen", "toch", "toen", "tot", "u", "uit", "uw", "van", "veel", "voor", "waar", "was", "wat", "we", "werd", "wezen", "wie", "wil", "worden", "wordt", "zal", "ze", "zelf", "zich", "zij", "zijn", "zo", "zonder", "zou" } },
            { "ar", new[] { "أن", "إلى", "إن", "ال", "الذي", "الذين", "التي", "بال", "على", "في", "من", "هذا", "هذه", "هل", "و", "يا", "ما", "كان", "عن", "مع", "كل", "يكون", "ب", "ل", "لا", "لقد" } },
            { "hi", new[] { "अंदर", "अत", "अथवा", "अद", "अप", "अपना", "अपनी", "अपने", "अभि", "अभी", "आदि", "आप", "इत्यादि", "इन", "इनका", "इन्हीं", "इन्हें", "इन्होंने", "इस", "इसका", "इसकी", "इसके", "इसमें", "इसी", "इसे", "उन", "उनका", "उनकी", "उनके", "उनको", "उन्हीं", "उन्हें", "उन्होंने", "उस", "उसका", "उसकी", "उसके", "उसमें", "उसी", "उसे", "एक", "एवं", "एस", "ऐसे", "ओर", "और", "कइ", "कई", "कर", "करता", "करते", "करना", "करने", "करें", "कहते", "कहा", "का", "काफी", "कि", "कितना", "किन्हें", "किन्हों", "किया", "किर", "किस", "किसी", "किसे", "की", "कुछ", "कुल", "के", "को", "कोई", "कौन", "कौनसा", "गया", "घर", "जब", "जहाँ", "जा", "जितना", "जिन", "जिन्हें", "जिन्होंने", "जिस", "जिसके", "जिसमें", "जिसे", "जी", "जैसा", "जैसे", "जो", "तक", "तब", "तरह", "तिन", "तिन्हें", "तिन्हों", "तिस", "तिसे", "तो", "था", "थी", "थे", "दबारा", "दिया", "दुसरा", "दूसरे", "दो", "द्वारा", "न", "नहीं", "ना", "निचे", "निहायत", "नीचे", "ने", "पर", "पहले", "पूरा", "पे", "फिर", "बनी", "बही", "बहुत", "बाद", "बाल", "बिलकुल", "भी", "भितर", "भीतर", "मगर", "मानो", "मे", "में", "यदि", "यह", "यहाँ", "यही", "या", "यिह", "ये", "रखें", "रहा", "रहे", "राहा", "लिए", "लिये", "लेकिन", "व", "वग़ैरह", "वर्ग", "वह", "वहाँ", "वहीं", "वाले", "वुह", "वे", "सकता", "सकते", "सबसे", "सभी", "साथ", "साबुत", "सामने", "साभ", "सारा", "से", "सो", "ही", "हुआ", "हुई", "हुए", "हे", "है", "हैं", "हो", "होता", "होती", "होते", "होना", "होने" } },
            { "ja", new[] { "の", "に", "は", "を", "た", "が", "で", "て", "と", "し", "れ", "さ", "ある", "いる", "も", "する", "から", "な", "こと", "として" } },
            { "zh", new[] { "的", "一", "不", "在", "人", "有", "是", "为", "以", "于", "上", "他", "而", "后", "之", "来", "及", "了", "因", "下" } },
            { "ko", new[] { "아", "휴", "아이구", "아이쿠", "아이고", "어", "나", "우리", "저희", "따라", "의해", "을", "를", "에", "의", "가" } },
            { "tr", new[] { "acaba", "ama", "aslında", "az", "bazı", "belki", "biri", "birkaç", "birşey", "biz", "bu", "çok", "çünkü", "da", "daha", "de", "defa", "diye", "eğer", "en", "gibi", "hem", "hep", "hepsi", "her", "hiç", "için", "ise", "ki", "kim", "mı", "mu", "mü", "nasıl", "ne", "neden", "nerde", "nerede", "nereye", "niçin", "niye", "o", "sanki", "şey", "siz", "şu", "tüm", "ve", "veya", "ya", "yani" } },
            { "vi", new[] { "là", "của", "và", "các", "có", "được", "trong", "một", "cho", "những", "như", "đã", "với", "tại", "này", "về", "nhưng", "để" } },
            { "pl", new[] { "a", "aby", "ach", "acz", "aczkolwiek", "aj", "albo", "ale", "ani", "aż", "bardziej", "bardzo", "bo", "bowiem", "by", "byle", "byli", "było", "był", "była", "były", "będzie", "będą", "cali", "cała", "cały", "ci", "cię", "ciebie", "co", "cokolwiek", "coś", "czasami", "czasem", "czemu", "czy", "czyli", "daleko", "dla", "dlaczego", "dlatego", "do", "dobrze", "dokąd", "dość", "dużo", "dwa", "dwaj", "dwie", "dwoje", "dziś", "dzisiaj", "gdy", "gdyby", "gdyż", "gdzie", "gdziekolwiek", "gdzieś", "i", "ich", "ile", "im", "inna", "inne", "inny", "innych", "iż", "ja", "jak", "jakaś", "jakby", "jaki", "jakie", "jakiś", "jako", "jakoś", "je", "jeden", "jedna", "jedno", "jednak", "jednakże", "jego", "jej", "jako", "jeżeli", "już", "ją", "każdy", "kiedy", "kilka", "kimś", "kto", "ktokolwiek", "ktoś", "która", "które", "którego", "której", "który", "których", "którym", "którzy", "ku", "lat", "lecz", "lub", "ma", "mają", "mało", "mam", "mi", "mimo", "między", "mnie", "mną", "może", "można", "mój", "my", "na", "nawet", "nam", "nami", "nas", "nasz", "nasza", "nasze", "naszym", "nasi", "nic", "nich", "nie", "niech", "niego", "niej", "niemu", "nigdy", "nim", "nimi", "niż", "no", "o", "obok", "on", "ona", "one", "oni", "ono", "owszem", "pan", "po", "pod", "podczas", "pomimo", "ponad", "ponieważ", "powinien", "powinna", "powinni", "powinno", "poza", "prawie", "przecież", "przed", "przede", "przez", "przy", "roku", "również", "sam", "sama", "są", "się", "skąd", "sobie", "sobą", "sposób", "swoje", "ta", "tak", "taki", "takie", "także", "tam", "te", "tego", "tej", "temu", "ten", "teraz", "też", "totem", "tobie", "tobą", "trochę", "tu", "tutaj", "twoja", "twoje", "twój", "twój", "ty", "tych", "tylko", "tym", "u", "w", "wam", "wami", "was", "wasz", "wasza", "wasze", "we", "według", "wiele", "wielu", "więc", "więcej", "właśnie", "wszyscy", "wszystkich", "wszystkie", "wszystkim", "wszystko", "wtedy", "wy", "z", "za", "zawsze", "ze", "znowu", "znów", "został", "żaden", "żadna", "żadne", "żadnych", "że", "żeby" } },
            { "id", new[] { "ada", "adalah", "adanya", "adapun", "agak", "agaknya", "agar", "akan", "akankah", "akhir", "akhirnya", "aku", "akulah", "amat", "amatlah", "anda", "andalah", "antar", "antara", "antaranya", "apa", "apaan", "apabila", "apakah", "apalagi", "apatah", "artinya", "asal", "asalkan", "atas", "atau", "ataukah", "ataupun", "awal", "awalnya", "bagai", "bagaikan", "bagaimana", "bagaimanakah", "bagaimanapun", "bagi", "bagian", "bahkan", "bahwa", "bahwasanya", "baik", "bakal", "bakalan", "balik", "banyak", "bapak", "baru", "bawah", "beberapa", "begini", "beginian", "beginikah", "beginilah", "begitu", "begitukah", "begitulah", "begitupun", "bekerja", "belakang", "belakangan", "belum", "belumlah", "benar", "benarkah", "benarlah", "berada", "berakhir", "berakhirlah", "berakhirnya", "berapa", "berapakah", "berapalah", "berapapun", "berarti", "berawal", "berbagai", "bermacam", "bersama", "bersiap", "bersiap-siap", "bertanya", "bertanya-tanya", "berturut", "berturut-turut", "bertutur", "berujar", "berupa", "besar", "betul", "betulkah", "biasa", "biasanya", "bila", "bilakah", "bisa", "bisakah", "boleh", "bolehkah", "bolehlah", "buat", "bukan", "bukankah", "bukanlah", "bukannya", "bulan", "bung", "cara", "caranya", "cukup", "cukupkah", "cukuplah", "cuma", "dahulu", "dalam", "dan", "dapat", "dari", "daripada", "datang", "dekat", "demi", "demikian", "demikianlah", "dengan", "depan", "di", "dia", "diakhiri", "diakhirinya", "diawali", "diawalinya", "dibuat", "dibuatnya", "didapat", "didatangkan", "digunakan", "diibaratkan", "diibaratkannya", "diingat", "diingatkan", "diinginkan", "dijawab", "dijelaskan", "dijelaskannya", "dikarenakan", "dikatakan", "dikatakannya", "diketahui", "diketahuinya", "dikira", "dilakukan", "dilalui", "dilihat", "dimaksud", "dimaksudkan", "dimaksudkannya", "dimisalkan", "diminta", "dimintai", "dimisalkan", "dimulai", "dimulailah", "dimulainya", "dimungkinkan", "dini", "dipastikan", "diperbuat", "diperbuatnya", "dipergunakan", "diperkirakan", "diperlihatkan", "diperlukan", "diperlukannya", "dipersoalkan", "dipertanyakan", "dipunyai", "diri", "dirinya", "disampaikan", "disebut", "disebutkan", "disebutkannya", "disini", "disinilah", "disitu", "disitulah", "diserahkan", "disertai", "disertai", "disini", "disinilah", "disitu", "disitulah", "disini", "disinilah", "disitu", "disitulah", "disini", "disinilah", "disitu", "disitulah", "disini", "disinilah", "disitu", "disitulah", "disini", "disinilah", "disitu", "disitulah", "disini", "disinilah", "disitu", "disitulah", "disini", "disinilah", "disitu", "disitulah", "disini", "disinilah", "disitu", "disitulah", "disini", "disinilah", "disitu", "disitulah", "disini", "disinilah", "disitu", "disitulah", "disini", "disinilah", "disitu", "disitulah", "disini", "disinilah", "disitu", "disitulah", "disini", "disinilah", "disitu", "disitulah", "disini", "disinilah", "disitu", "disitulah", "disini", "disinilah", "disitu", "disitulah" } },
            { "th", new[] { "และ", "ใน", "ที่", "ของ", "ให้", "ได้", "จะ", "ความ", "เป็น", "มี", "การ", "ว่า", "ไป", "ด้วย", "แต่", "ก็", "จาก", "มา", "ๆ", "เพื่อ" } },
            { "sv", new[] { "och", "det", "att", "i", "en", "jag", "hon", "som", "han", "på", "den", "med", "var", "sig", "för", "så", "till", "är", "men", "ett", "om", "hade", "de", "av", "icke", "mig", "du", "henne", "då", "sin", "nu", "har", "inte", "hans", "honom", "skulle", "hennes", "där", "min", "man", "ej", "vid", "kunde", "något", "från", "ut", "när", "efter", "upp", "vi", "dem", "vara", "vad", "över", "än", "dig", "kan", "sina", "här", "ha", "mot", "alla", "under", "någon", "eller", "allt", "mycket", "sedan", "ju", "denna", "själv", "detta", "åt", "utan", "varit", "hur", "ingen", "mitt", "ni", "bli", "blev", "oss", "din", "dessa", "några", "deras", "blir", "mina", "samma", "vilken", "er", "sådan", "vår", "blivit", "dess", "inom", "mellan", "sådana", "våra", "varföre", "varför", "vilka", "fort", "ännu", "bakom", "nära", "nuvarande", "medan", "åtminstone", "få", "först", "hurudan", "vänster", "höger", "större", "störst", "alltså", "vilket", "viss", "verkligen" } },
            { "no", new[] { "og", "i", "jeg", "det", "at", "en", "et", "den", "til", "er", "som", "på", "de", "med", "han", "av", "ikke", "ikke", "der", "så", "var", "meg", "seg", "men", "ett", "om", "hadde", "hun", "nå", "over", "da", "ved", "fra", "denne", "noen", "ut", "sin", "dem", "vi", "har", "hva", "skal", "selv", "sier", "alle", "vil", "her", "før", "blir", "skulle", "opp", "deres", "kan", "hans", "hvor", "eller", "alt", "dette", "sine", "henne", "seg", "deres", "hvor", "eller", "alt", "dette", "sine", "henne" } },
            { "da", new[] { "og", "i", "jeg", "det", "at", "en", "den", "til", "er", "som", "på", "de", "med", "han", "af", "for", "ikke", "der", "var", "mig", "sig", "men", "ét", "om", "vi", "min", "havde", "ham", "hun", "nu", "over", "da", "fra", "meget", "dig", "anden", "hende", "mine", "alt", "meget", "sit", "sine", "her", "mod", "os", "efter", "selv", "da", "alle", "vil", "blev", "kun", "denne", "end", "dog", "ret", "op", "skal", "skulle", "man", "da", "alt", "meget", "sit", "sine", "her", "mod", "os", "efter", "selv", "da", "alle", "vil", "blev", "kun", "denne", "end", "dog", "ret", "op", "skal", "skulle", "man" } },
            { "fi", new[] { "olla", "ole", "olen", "olet", "on", "olemme", "olette", "ovat", "ole_en", "ole_et", "ole_ei", "ole_emme", "ole_ette", "ole_eivät", "oli", "olisi", "olisit", "olisi", "olisimme", "olisitte", "olisivat", "olit", "olimme", "olitte", "olivat", "ollut", "olleet", "en", "et", "ei", "emme", "ette", "eivät", "minä", "minun", "minua", "minussa", "minusta", "minuun", "minulla", "minulta", "minulle", "sinä", "sinun", "sinua", "sinussa", "sinusta", "sinuun", "sinulla", "sinulta", "sinulle", "hän", "hänen", "häntä", "hänessä", "hänestä", "häneen", "hänellä", "häneltä", "hänelle", "me", "meidän", "meitä", "meissä", "meistä", "meihin", "meillä", "meiltä", "meille", "te", "teidän", "teitä", "teissä", "teistä", "teihin", "teillä", "teiltä", "teille", "he", "heidän", "heitä", "heissä", "heistä", "heihin", "heillä", "heiltä", "heille", "tämä", "tämän", "tätä", "tässä", "tästä", "tähän", "tällä", "tältä", "tälle", "tuo", "tuon", "tuota", "tuossa", "tuosta", "tuohon", "tuolla", "tuolta", "tuolle", "se", "sen", "sitä", "siinä", "siitä", "siihen", "sillä", "siltä", "sille", "nämä", "näiden", "näitä", "näissä", "näistä", "näihin", "näillä", "näiltä", "näille", "nuo", "nuoiden", "nuoita", "nuoissa", "nuoista", "nuoihin", "nuoilla", "nuoilta", "nuoille", "ne", "niiden", "niitä", "niissä", "niistä", "niihin", "niillä", "niiltä", "niille", "kuka", "kenen", "ketä", "kenessä", "kenestä", "keneen", "kenellä", "keneltä", "kenelle", "ketkä", "keiden", "keitä", "keissä", "keistä", "keihin", "keillä", "keiltä", "keille", "mikä", "minkä", "mitä", "missä", "mistä", "mihin", "millä", "miltä", "mille", "mitkä", "miden", "mitä", "missä", "mistä", "mihin", "millä", "miltä", "mille", "joka", "jonka", "jota", "jossa", "josta", "johon", "jolla", "jolta", "jolle", "jotka", "joiden", "joita", "joissa", "joista", "joihin", "joilla", "joilta", "joille", "että", "ja", "jos", "koska", "mutta", "vaikka", "kuin", "niin", "nii", "noin", "suoraan", "ihan", "siis", "tässä", "sitten", "viime", "vuoden", "vuonna", "vuosi", "kaksi", "kolme", "neljä", "viisi", "kuusi", "seitsemän", "kahdeksan", "yhdeksän", "kymmenen", "ensimmäinen", "toinen", "kolmas", "neljäs", "viides", "kuudes", "seitsemäs", "kahdeksas", "yhdeksäs", "kymmenes" } },
            { "el", new[] { "από", "για", "ένα", "έναν", "ένας", "ένα", "και", "με", "να", "ο", "οι", "στο", "στους", "της", "το", "τον", "του", "των" } },
            { "he", new[] { "את", "של", "על", "עם", "הוא", "היא", "הם", "הן", "זה", "זו", "אלה", "אלו", "אם", "או", "גם", "כל", "מה", "מי", "כדי", "לא" } },
            { "pl", new[] { "a", "aby", "ach", "acz", "aczkolwiek", "aj", "albo", "ale", "ani", "aż", "bardziej", "bardzo", "bo", "bowiem", "by", "byle", "byli", "było", "był", "była", "były", "będzie", "będą", "cali", "cała", "cały", "ci", "cię", "ciebie", "co", "cokolwiek", "coś", "czasami", "czasem", "czemu", "czy", "czyli", "daleko", "dla", "dlaczego", "dlatego", "do", "dobrze", "dokąd", "dość", "dużo", "dwa", "dwaj", "dwie", "dwoje", "dziś", "dzisiaj", "gdy", "gdyby", "gdyż", "gdzie", "gdziekolwiek", "gdzieś", "i", "ich", "ile", "im", "inna", "inne", "inny", "innych", "iż", "ja", "jak", "jakaś", "jakby", "jaki", "jakie", "jakiś", "jako", "jakoś", "je", "jeden", "jedna", "jedno", "jednak", "jednakże", "jego", "jej", "jako", "jeżeli", "już", "ją", "każdy", "kiedy", "kilka", "kimś", "kto", "ktokolwiek", "ktoś", "która", "które", "którego", "której", "który", "których", "którym", "którzy", "ku", "lat", "lecz", "lub", "ma", "mają", "mało", "mam", "mi", "mimo", "między", "mnie", "mną", "może", "można", "mój", "my", "na", "nawet", "nam", "nami", "nas", "nasz", "nasza", "nasze", "naszym", "nasi", "nic", "nich", "nie", "niech", "niego", "niej", "niemu", "nigdy", "nim", "nimi", "niż", "no", "o", "obok", "on", "ona", "one", "oni", "ono", "owszem", "pan", "po", "pod", "podczas", "pomimo", "ponad", "ponieważ", "powinien", "powinna", "powinni", "powinno", "poza", "prawie", "przecież", "przed", "przede", "przez", "przy", "roku", "również", "sam", "sama", "są", "się", "skąd", "sobie", "sobą", "sposób", "swoje", "ta", "tak", "taki", "takie", "także", "tam", "te", "tego", "tej", "temu", "ten", "teraz", "też", "totem", "tobie", "tobą", "trochę", "tu", "tutaj", "twoja", "twoje", "twój", "twój", "ty", "tych", "tylko", "tym", "u", "w", "wam", "wami", "was", "wasz", "wasza", "wasze", "we", "według", "wiele", "wielu", "więc", "więcej", "właśnie", "wszyscy", "wszystkich", "wszystkie", "wszystkim", "wszystko", "wtedy", "wy", "z", "za", "zawsze", "ze", "znowu", "znów", "został", "żaden", "żadna", "żadne", "żadnych", "że", "żeby" } }
        };

        private static readonly HashSet<string> GlobalStopWords = new(
            StopWords.Values.SelectMany(x => x),
            StringComparer.OrdinalIgnoreCase
        );

        public static long GetSemanticFingerprint(string input)
        {
            // 1. Clean & Lowercase
            if (string.IsNullOrEmpty(input)) return 0;
            string pattern = @"[^\p{L}\p{N}\p{Sc}\p{Sm}]+";
            IEnumerable<string> words = [.. Regex.Split(input, pattern, RegexOptions.IgnoreCase)
                .Where(w => !string.IsNullOrWhiteSpace(w) && w.Length > 1)
                .Select(w => w.ToLowerInvariant())];

            // 2. Filter for Nouns (NN) and Negations (NOT)
            var coreContent = words
                .Where(w => w.Length > 1 && !GlobalStopWords.Contains(w))
                .Select(w => w.ToLowerInvariant())
                .OrderBy(x => x); // Sorting makes "A and B" the same as "B and A"

            // 3. Join and Hash
            return GetFNV1aHash(string.Join("|", coreContent));
        }

    }
}
