global using Extensions.ForeignEntity;
global using Extensions.PrometheusTypes;
global using Microsoft.EntityFrameworkCore;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using DateTime = System.DateTime;
global using Type = System.Type;
global using UserData;
