<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<OutputType>Library</OutputType>
		<HasRuntimeOutput>false</HasRuntimeOutput>
		<RootNamespace>UserData</RootNamespace>
		<AssemblyName>$(RootNamespace)</AssemblyName>
	</PropertyGroup>
	

	<ItemGroup>
	  <ProjectReference Include="..\DataShared\DataShared.csproj" />
	</ItemGroup>

</Project>
