global using Extensions.ForeignEntity;
global using Extensions.PrometheusTypes;
global using Extensions.JsonVoorhees;
global using FlashData.Entities;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.Authorization;
global using Microsoft.AspNetCore.Components.Rendering;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.JSInterop;
global using RazorSharp.Extensions;
global using RazorSharp.Layout;
global using RazorSharp.Services;
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Net;
global using System.Text.Json;
global using System.Threading;
global using System.Threading.Tasks;
global using UserData;
global using UserData.Entities;
global using File = FlashData.Entities.File;
global using TaskExtensions = Extensions.PrometheusTypes.TaskExtensions;
global using IComponent = Microsoft.AspNetCore.Components.IComponent;


