<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<OutputType>Library</OutputType>
		<HasRuntimeOutput>false</HasRuntimeOutput>
		<RootNamespace>RazorSharp</RootNamespace>
		<AssemblyName>$(RootNamespace)</AssemblyName>
	</PropertyGroup>
	
	<ItemGroup>
		<Content Update="wwwroot\triangle.svg">
			<Color>transparent</Color>
		</Content>
	</ItemGroup>


	<ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.*-*" />
	  <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.*-*" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\DataShared\DataShared.csproj" />
	  <ProjectReference Include="..\Extensions\Extensions.csproj" />
	</ItemGroup>

</Project>
